"""Generate voice-options.ts from live edge-tts catalog."""
from __future__ import annotations

import asyncio
import json
import re
from pathlib import Path

import edge_tts

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "app" / "src" / "lib" / "voice-options.ts"
BUNDLED_CATALOG = ROOT / "worker" / "data" / "edge-voices-catalog.json"

LOCALE_LABEL = {
    "vi-VN": "VI",
    "en-US": "EN-US",
    "en-GB": "EN-GB",
    "en-AU": "EN-AU",
    "en-CA": "EN-CA",
    "en-IN": "EN-IN",
    "en-IE": "EN-IE",
    "en-NZ": "EN-NZ",
    "en-ZA": "EN-ZA",
    "en-HK": "EN-HK",
    "en-SG": "EN-SG",
    "en-PH": "EN-PH",
    "ja-JP": "JA",
    "ko-KR": "KO",
    "zh-CN": "ZH",
    "th-TH": "TH",
    "id-ID": "ID",
}

TONE = {
    "Female": "natural",
    "Male": "clear",
}


LABEL_OVERRIDES = {
    "vi-VN-HoaiMyNeural": "Hoài My",
    "vi-VN-NamMinhNeural": "Nam Minh",
}


def label_from_voice(v: dict) -> str:
    short = str(v.get("ShortName", ""))
    if short in LABEL_OVERRIDES:
        return LABEL_OVERRIDES[short]
    friendly = str(v.get("FriendlyName") or "")
    friendly = re.sub(r"^Microsoft\s+", "", friendly)
    friendly = re.sub(r"\s+Online.*$", "", friendly)
    friendly = re.sub(r"\s*\(Natural\).*$", "", friendly)
    label = friendly.strip() or short.split("-")[-1].replace("Neural", "")
    label = label.replace("Multilingual", " (ML)")
    return label


def locale_bucket(short: str) -> str:
    parts = short.split("-")
    if len(parts) >= 2:
        return f"{parts[0]}-{parts[1]}"
    return short


def sort_key(v: dict) -> tuple:
    short = str(v.get("ShortName", ""))
    locale = locale_bucket(short)
    tier = {
        "en-US": 0,
        "vi-VN": 1,
    }.get(locale, 2 if locale.startswith("en-") else 3)
    return (tier, locale, short)


async def main() -> None:
    catalog = await edge_tts.list_voices()
    neural = [v for v in catalog if str(v.get("ShortName", "")).endswith("Neural")]
    picked = list(neural)
    picked.sort(key=sort_key)

    lines = [
        "export type VoiceOption = {",
        "  id: string;",
        "  label: string;",
        "  gender: string;",
        "  locale: string;",
        "  tone: string;",
        "  recommended?: boolean;",
        "};",
        "",
        "/** Live edge-tts neural voices (322) — generated by worker/scripts/generate-voice-options.py */",
        "export const VOICE_OPTIONS: VoiceOption[] = [",
    ]
    for v in picked:
        short = str(v["ShortName"])
        locale = locale_bucket(short)
        gender = "♀" if str(v.get("Gender")) == "Female" else "♂"
        label = label_from_voice(v)
        tone = TONE.get(str(v.get("Gender")), "natural")
        rec = ", recommended: true" if short == "en-US-JennyNeural" else ""
        locale_code = locale
        lines.append(
            f"  {{ id: '{short}', label: '{label}', gender: '{gender}', locale: '{locale_code}', tone: '{tone}'{rec} }},"
        )
    lines.append("];")
    lines.append("")
    OUT.write_text("\n".join(lines), encoding="utf-8")
    BUNDLED_CATALOG.parent.mkdir(parents=True, exist_ok=True)
    bundled = [
        {
            "ShortName": str(v["ShortName"]),
            "Locale": str(v.get("Locale") or locale_bucket(str(v["ShortName"]))),
            "Gender": str(v.get("Gender") or "Female"),
            "FriendlyName": str(v.get("FriendlyName") or v["ShortName"]),
        }
        for v in picked
    ]
    BUNDLED_CATALOG.write_text(json.dumps(bundled, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"wrote {len(picked)} voices -> {OUT}")
    print(f"wrote {len(bundled)} voices -> {BUNDLED_CATALOG}")


if __name__ == "__main__":
    asyncio.run(main())
